
Turn 3
================================================================
warning: entity 1 was directed to use 1 halite to move north, but only 0 halite was available
At command 2 of 3:
    1   m 3 e
>>> 2   m 1 n
    3   g

warning: owned entities 3, 1 collided on cell (9, 16) as the result of moves on this turn
At command 1 of 3:
>>> 1   m 3 e
    2   m 1 n
    3   g


Turn 6
================================================================
warning: owned entities 9, 5 collided on cell (7, 16) as the result of moves on this turn
At command 1 of 3:
>>> 1   m 9 w
    2   m 5 e
    3   m 7 s

Other commands that placed an entity on this cell:
    1   m 9 w
>>> 2   m 5 e
    3   m 7 s


Turn 7
================================================================
warning: entity 7 was directed to use 3 halite to move south, but only 0 halite was available
At command 1 of 1:
>>> 1   m 7 s


Turn 56
================================================================
error: communication error with bot: read failed, errno was: 0 (Success)
Last input received was:


Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 72, in <module>
    command_queue.append(ship.move(deliver(ship, game_map, my_dropoffs_positions)))
  File "MyBot.py", line 45, in deliver
    return naive_navigate(ship, best_vect, 2)
NameError: name 'naive_navigate' is not defined

